export type Motif = 'leaf' | 'wheat' | 'flame' | 'drip' | 'grape' | 'knife' | 'oven' | 'fish';
export type Origin = 'ru' | 'sr';

export interface Dish {
  id: string;
  origin: Origin;
  cats: string[];
  time: number; // minutes
  diff: 0 | 1 | 2;
  cal: number;
  accent: string;
  secondary: string;
  motif: Motif;
  ru: { name: string; cat: string; desc: string };
  sr: { name: string; cat: string; desc: string };
}

export const DISHES: Dish[] = [
  // ─── RUSSIAN DISHES ───────────────────────────────────────────────────────────
  {
    id: 'sarma',
    origin: 'ru',
    cats: ['Главное', 'Балканский гриль'],
    time: 180,
    diff: 2,
    cal: 320,
    accent: '#8B2635',
    secondary: '#5A1520',
    motif: 'flame',
    ru: { name: 'Сарма', cat: 'Главное блюдо', desc: 'Голубцы в квашеной капусте — сербская душа русской кухни. Готовятся медленно, на малом огне, источая пряный аромат паприки и копчёностей.' },
    sr: { name: 'Sarma', cat: 'Glavno jelo', desc: 'Kupus rolnice sa mlevenim mesom — srpska duša ruske kuhinje. Kuvaju se polako, na tihoj vatri, šireći miris paprike i sušenog mesa.' },
  },
  {
    id: 'pelmeni',
    origin: 'ru',
    cats: ['Главное'],
    time: 60,
    diff: 1,
    cal: 280,
    accent: '#C8893E',
    secondary: '#8B5E1E',
    motif: 'wheat',
    ru: { name: 'Пельмени', cat: 'Главное блюдо', desc: 'Символ русской зимы — маленькие ушки из теста с сочной мясной начинкой. Подаются со сметаной и свежемолотым перцем.' },
    sr: { name: 'Pelmeni', cat: 'Glavno jelo', desc: 'Simbol ruske zime — mali trbušci od testa sa sočnim mesnim punjenjem. Serviraju se sa kiselom pavlakom i svežim biberom.' },
  },
  {
    id: 'borsh',
    origin: 'ru',
    cats: ['Супы'],
    time: 90,
    diff: 1,
    cal: 180,
    accent: '#8B2635',
    secondary: '#4A1015',
    motif: 'leaf',
    ru: { name: 'Борщ', cat: 'Суп', desc: 'Багряный суп с мягкой свёклой, капустой и сочной говядиной. Настаивается сутки — и становится вдвое вкуснее.' },
    sr: { name: 'Boršč', cat: 'Supa', desc: 'Grimizna supa sa reپom, kupusom i sočnom govedinom. Odležava dan i postaje duplo ukusnija.' },
  },
  {
    id: 'shchi',
    origin: 'ru',
    cats: ['Супы'],
    time: 75,
    diff: 0,
    cal: 150,
    accent: '#3F5944',
    secondary: '#2A3D2E',
    motif: 'leaf',
    ru: { name: 'Щи', cat: 'Суп', desc: 'Щи да каша — пища наша. Капустный суп с кореньями и мясом, сваренный в чугунке — простой и согревающий.' },
    sr: { name: 'Šči', cat: 'Supa', desc: 'Stara ruska kupusna supa sa korenom povrća i mesom, kuvana u glinenoj posudi.' },
  },
  {
    id: 'okroshka',
    origin: 'ru',
    cats: ['Супы', 'За 30 минут'],
    time: 20,
    diff: 0,
    cal: 120,
    accent: '#6B8F6B',
    secondary: '#3F5944',
    motif: 'drip',
    ru: { name: 'Окрошка', cat: 'Холодный суп', desc: 'Летний холодный суп на квасе с огурцом, редиской, яйцом и варёным мясом. Освежает в самый жаркий день.' },
    sr: { name: 'Okroška', cat: 'Hladna supa', desc: 'Letnja hladna supa na kefiru sa krastavcima, rotkvicom i jajima. Osvežava u najtoplijem danu.' },
  },
  {
    id: 'ukha',
    origin: 'ru',
    cats: ['Супы'],
    time: 45,
    diff: 1,
    cal: 130,
    accent: '#5B7FA6',
    secondary: '#3A5070',
    motif: 'fish',
    ru: { name: 'Уха', cat: 'Суп', desc: 'Прозрачный рыбный бульон с судаком или щукой, луком и лавровым листом. Лучшее блюдо после рыбалки.' },
    sr: { name: 'Uha', cat: 'Riblja čorba', desc: 'Bistra riblja čorba sa štuka ili smudja, lukom i lovorovim listom.' },
  },
  {
    id: 'rassolnik',
    origin: 'ru',
    cats: ['Супы'],
    time: 80,
    diff: 1,
    cal: 160,
    accent: '#7A6B3E',
    secondary: '#4A3E1E',
    motif: 'drip',
    ru: { name: 'Рассольник', cat: 'Суп', desc: 'Кисловатый суп с солёными огурцами, перловкой и почками. Идеален после праздничного застолья.' },
    sr: { name: 'Rasoljnik', cat: 'Supa', desc: 'Kisela supa sa kiselim krastavcima, ješmom i bubrezima. Idealna za oporavak.' },
  },
  {
    id: 'solyanka',
    origin: 'ru',
    cats: ['Супы'],
    time: 70,
    diff: 1,
    cal: 200,
    accent: '#A05C2E',
    secondary: '#6A3A1A',
    motif: 'flame',
    ru: { name: 'Солянка', cat: 'Суп', desc: 'Густой мясной суп с несколькими видами мяса, оливками и лимоном. Кислый, солёный, пряный — незабываемый.' },
    sr: { name: 'Solyanka', cat: 'Supa', desc: 'Gusta mesna supa sa više vrsta mesa, maslinama i limunom. Kiselo, slano, začinjeno.' },
  },
  {
    id: 'beef-stroganov',
    origin: 'ru',
    cats: ['Главное'],
    time: 50,
    diff: 1,
    cal: 380,
    accent: '#9B5C3A',
    secondary: '#6A3A1E',
    motif: 'knife',
    ru: { name: 'Бефстроганов', cat: 'Главное блюдо', desc: 'Тонкие полоски говядины в нежном сметанном соусе с луком и горчицей. Блюдо графской кухни XIX века.' },
    sr: { name: 'Bef Stroganov', cat: 'Glavno jelo', desc: 'Tanke trake govedine u nežnom kremastom sosu sa lukom i senfom.' },
  },
  {
    id: 'pozharskie',
    origin: 'ru',
    cats: ['Главное'],
    time: 40,
    diff: 1,
    cal: 350,
    accent: '#C8893E',
    secondary: '#8B5E1E',
    motif: 'oven',
    ru: { name: 'Пожарские котлеты', cat: 'Главное блюдо', desc: 'Нежные куриные котлеты в хрустящих сухарях со сливочным маслом внутри. Рецепт из Торжка XIX века.' },
    sr: { name: 'Požarski kotleti', cat: 'Glavno jelo', desc: 'Nežni pileći kotleti u hrskavim prezlama sa puterom unutra.' },
  },
  {
    id: 'kulebyaka',
    origin: 'ru',
    cats: ['Выпечка'],
    time: 120,
    diff: 2,
    cal: 420,
    accent: '#A07040',
    secondary: '#6B4820',
    motif: 'wheat',
    ru: { name: 'Кулебяка', cat: 'Пирог', desc: 'Торжественный многослойный пирог с несколькими начинками — рыбой, рисом, луком и грибами. Блюдо для особых случаев.' },
    sr: { name: 'Kulebaka', cat: 'Pita', desc: 'Svečana slojevita pita sa ribom, pirinčem, lukom i pečurkama.' },
  },
  {
    id: 'rastegai',
    origin: 'ru',
    cats: ['Выпечка', 'Закуски'],
    time: 90,
    diff: 2,
    cal: 280,
    accent: '#8B6B3E',
    secondary: '#5A4220',
    motif: 'fish',
    ru: { name: 'Расстегаи', cat: 'Пирожки', desc: 'Открытые пирожки с рыбной начинкой, которые «расстёгивают» верхушку для добавления бульона. Петербургский деликатес.' },
    sr: { name: 'Rastejai', cat: 'Piroške', desc: 'Otvorene piroške sa ribom — u koje se sipa čorba. Delikatesa iz Sankt Peterburga.' },
  },
  {
    id: 'vatruški',
    origin: 'ru',
    cats: ['Выпечка', 'Десерты'],
    time: 70,
    diff: 1,
    cal: 240,
    accent: '#D4986A',
    secondary: '#9B6A3E',
    motif: 'oven',
    ru: { name: 'Ватрушки', cat: 'Выпечка', desc: 'Мягкие дрожжевые лепёшки с нежной творожной начинкой. Аромат советского детства и домашней кухни.' },
    sr: { name: 'Vatruške', cat: 'Pecivo', desc: 'Meke kvasne lepinje sa svežim sirom. Miris domaćeg doma i detinjstva.' },
  },
  {
    id: 'bliny',
    origin: 'ru',
    cats: ['Выпечка', 'Десерты', 'За 30 минут'],
    time: 30,
    diff: 0,
    cal: 220,
    accent: '#C8893E',
    secondary: '#8B5E1E',
    motif: 'drip',
    ru: { name: 'Блины', cat: 'Блины', desc: 'Тонкие пшеничные блины на молоке — символ Масленицы. Подаются со сметаной, икрой или вареньем.' },
    sr: { name: 'Blini', cat: 'Palačinke', desc: 'Tanki pšenični palačinci na mleku — simbol ruskog karnevala. Serviraju se sa kiselom pavlakom ili džemom.' },
  },
  {
    id: 'syrniki',
    origin: 'ru',
    cats: ['Выпечка', 'Десерты', 'За 30 минут'],
    time: 25,
    diff: 0,
    cal: 280,
    accent: '#E8C06A',
    secondary: '#C8893E',
    motif: 'oven',
    ru: { name: 'Сырники', cat: 'Завтрак', desc: 'Творожные оладьи, обжаренные до румяной корочки. Мягкие внутри, хрустящие снаружи — идеальный завтрак.' },
    sr: { name: 'Sirniki', cat: 'Doručak', desc: 'Pohani sir (quark) kolačići, prženi do zlatne korice. Meki iznutra, hrskavi spolja.' },
  },
  {
    id: 'medovik',
    origin: 'ru',
    cats: ['Десерты'],
    time: 150,
    diff: 2,
    cal: 450,
    accent: '#C8893E',
    secondary: '#8B5E1E',
    motif: 'drip',
    ru: { name: 'Медовик', cat: 'Торт', desc: 'Многослойный медовый торт со сметанным кремом, пропитывающийся сутки. Нежный, ароматный, незабываемый.' },
    sr: { name: 'Medovik', cat: 'Torta', desc: 'Višeslojna torta od meda sa kiselom pavlakom, koja se odlежava dan. Nežna i nezaboravna.' },
  },
  {
    id: 'napoleon',
    origin: 'ru',
    cats: ['Десерты'],
    time: 180,
    diff: 2,
    cal: 480,
    accent: '#9B7B3F',
    secondary: '#5A4222',
    motif: 'wheat',
    ru: { name: 'Наполеон', cat: 'Торт', desc: 'Тысячелистник из слоёного теста с заварным кремом. Хрустящий и нежный одновременно — пирожное на все времена.' },
    sr: { name: 'Napoleon', cat: 'Torta', desc: 'Krempita od lisnatog testa sa kremom. Hrskava i nežna istovremeno.' },
  },
  {
    id: 'guryevskaya',
    origin: 'ru',
    cats: ['Десерты'],
    time: 40,
    diff: 1,
    cal: 380,
    accent: '#D4986A',
    secondary: '#A06A3E',
    motif: 'drip',
    ru: { name: 'Гурьевская каша', cat: 'Десерт', desc: 'Манная каша с запечёнными пенками, орехами и вареньем. Блюдо министра финансов Гурьева — роскошь из простого.' },
    sr: { name: 'Gurjevska kaša', cat: 'Desert', desc: 'Griz sa pečenim korama, orašastim plodovima i džemom.' },
  },
  {
    id: 'olive',
    origin: 'ru',
    cats: ['Закуски', 'Популярное'],
    time: 30,
    diff: 0,
    cal: 200,
    accent: '#3F5944',
    secondary: '#2A3D2E',
    motif: 'leaf',
    ru: { name: 'Оливье', cat: 'Салат', desc: 'Салат с варёными овощами, яйцами, колбасой и солёными огурцами. Символ Нового года и любого праздничного стола.' },
    sr: { name: 'Olivije', cat: 'Salata', desc: 'Salata sa kuvanim povrćem, jajima, kobasicom i kiselim krastavcima.' },
  },
  {
    id: 'herring-coat',
    origin: 'ru',
    cats: ['Закуски', 'Популярное'],
    time: 40,
    diff: 0,
    cal: 220,
    accent: '#7B6B9B',
    secondary: '#4A3A6A',
    motif: 'fish',
    ru: { name: 'Селёдка под шубой', cat: 'Салат', desc: 'Слоёный салат с селёдкой, свёклой, морковью и майонезом. Ярко-пурпурный, сытный и неизменно вкусный.' },
    sr: { name: 'Haringa u kaputu', cat: 'Salata', desc: 'Slojevita salata sa haringom, ciklom, šargarepom i majonezom.' },
  },
  {
    id: 'zharkoye',
    origin: 'ru',
    cats: ['Главное'],
    time: 100,
    diff: 1,
    cal: 420,
    accent: '#8B5C3A',
    secondary: '#5A3A1E',
    motif: 'oven',
    ru: { name: 'Жаркое', cat: 'Главное блюдо', desc: 'Говядина с картофелем, запечённая в горшочке с луком и лавровым листом. Деревенская простота и богатый вкус.' },
    sr: { name: 'Žarkoje', cat: 'Glavno jelo', desc: 'Govedina sa krompirima pečena u lončiću sa lukom i lovorovim listom.' },
  },
  {
    id: 'kiev-cutlet',
    origin: 'ru',
    cats: ['Главное', 'Популярное'],
    time: 50,
    diff: 2,
    cal: 400,
    accent: '#D4986A',
    secondary: '#9B6A3E',
    motif: 'knife',
    ru: { name: 'Котлета по-киевски', cat: 'Главное блюдо', desc: 'Куриная котлета с маслом внутри в хрустящей золотой панировке. Разрезаешь — и течёт сливочное масло.' },
    sr: { name: 'Kijevski kotlet', cat: 'Glavno jelo', desc: 'Piletina sa puterom iznutra u hrskavim prezlama. Preseče se i maslac curi.' },
  },
  {
    id: 'pastila',
    origin: 'ru',
    cats: ['Десерты', 'За 30 минут'],
    time: 20,
    diff: 0,
    cal: 120,
    accent: '#E8C4B8',
    secondary: '#C8893E',
    motif: 'leaf',
    ru: { name: 'Пастила', cat: 'Сладкое', desc: 'Воздушное яблочное лакомство — белоснежное, слегка кисловатое. Старинное русское сладкое, известное с XIV века.' },
    sr: { name: 'Pastila', cat: 'Slatkiš', desc: 'Vazdušasta jabučna poslastica — snežnobela, blago kiselkasta. Stari ruski slatkiš.' },
  },
  {
    id: 'kvashenaya',
    origin: 'ru',
    cats: ['Закуски', 'Постные'],
    time: 4320,
    diff: 0,
    cal: 30,
    accent: '#6B8F6B',
    secondary: '#3F5944',
    motif: 'leaf',
    ru: { name: 'Квашеная капуста', cat: 'Заготовка', desc: 'Хрустящая белокочанная капуста, сквашенная с морковью и солью. Пробиотик, витамины и вкус русской зимы.' },
    sr: { name: 'Kiseli kupus', cat: 'Zimnica', desc: 'Hrskavi beli kupus fermentiran sa šargarepom i solju. Probiotik i ukus ruske zime.' },
  },
  {
    id: 'pirozhki',
    origin: 'ru',
    cats: ['Выпечка', 'Популярное'],
    time: 90,
    diff: 1,
    cal: 260,
    accent: '#C8893E',
    secondary: '#8B5E1E',
    motif: 'oven',
    ru: { name: 'Пирожки', cat: 'Выпечка', desc: 'Мягкие дрожжевые пирожки с мясом, капустой или картошкой. Запах из духовки — это и есть дом.' },
    sr: { name: 'Piroške', cat: 'Pecivo', desc: 'Meke piroške sa mesom, kupusom ili krompirom. Miris iz rerne — to je dom.' },
  },

  // ─── SERBIAN DISHES ───────────────────────────────────────────────────────────
  {
    id: 'cevapi',
    origin: 'sr',
    cats: ['Балканский гриль', 'Популярное'],
    time: 30,
    diff: 1,
    cal: 380,
    accent: '#8B2635',
    secondary: '#5A1520',
    motif: 'flame',
    ru: { name: 'Ћевапи', cat: 'Балканский гриль', desc: 'Жареные мясные колбаски из говядины и свинины с луком в лаваше. Символ балканского уличного фастфуда.' },
    sr: { name: 'Ćevapi', cat: 'Roštilj', desc: 'Pečene mesne kobasice od govedine i svinjetine sa lukom u lepinji. Simbol balkanske kuhinje.' },
  },
  {
    id: 'pljeskavica',
    origin: 'sr',
    cats: ['Балканский гриль', 'Популярное'],
    time: 25,
    diff: 0,
    cal: 450,
    accent: '#9B5C3A',
    secondary: '#6A3A1E',
    motif: 'flame',
    ru: { name: 'Плескавица', cat: 'Балканский гриль', desc: 'Сербский бургер — крупная мясная котлета на гриле с луком и зеленью. Сочная, ароматная, неповторимая.' },
    sr: { name: 'Pljeskavica', cat: 'Roštilj', desc: 'Srpski burger — velika mesna pljeskavica na roštilju sa lukom i začinima.' },
  },
  {
    id: 'pljeskavica-kajmak',
    origin: 'sr',
    cats: ['Балканский гриль'],
    time: 30,
    diff: 1,
    cal: 520,
    accent: '#C8893E',
    secondary: '#8B5E1E',
    motif: 'drip',
    ru: { name: 'Плескавица с каймаком', cat: 'Балканский гриль', desc: 'Плескавица с начинкой из каймака — тающего сливочного сыра. Фаршированное удовольствие.' },
    sr: { name: 'Pljeskavica na kajmaku', cat: 'Roštilj', desc: 'Pljeskavica punjena kajmakom — kremastim sirom. Punjeno zadovoljstvo.' },
  },
  {
    id: 'karadjordjevica',
    origin: 'sr',
    cats: ['Главное', 'Популярное'],
    time: 40,
    diff: 2,
    cal: 480,
    accent: '#8B2635',
    secondary: '#5A1520',
    motif: 'knife',
    ru: { name: 'Карађорђева шницла', cat: 'Главное блюдо', desc: 'Рулет из свинины с каймаком в хрустящей панировке с паприкой. Назван в честь сербского героя.' },
    sr: { name: 'Karađorđeva šnicla', cat: 'Glavno jelo', desc: 'Svinjski rolat sa kajmakom u hrskavim prezlama sa paprikom. Nazvan po srpskom junaku.' },
  },
  {
    id: 'raznjici',
    origin: 'sr',
    cats: ['Балканский гриль'],
    time: 35,
    diff: 0,
    cal: 360,
    accent: '#A05C2E',
    secondary: '#6A3A1A',
    motif: 'flame',
    ru: { name: 'Ражњичи', cat: 'Шашлык', desc: 'Сербский шашлык — кусочки свинины на шпажках, маринованные в специях и жаренные на углях.' },
    sr: { name: 'Ražnjići', cat: 'Roštilj', desc: 'Srpski šiš-ćevap — komadi svinjetine na ražnju, marinirani u začinima na ugljevlju.' },
  },
  {
    id: 'burek',
    origin: 'sr',
    cats: ['Выпечка', 'Популярное'],
    time: 50,
    diff: 1,
    cal: 380,
    accent: '#D4986A',
    secondary: '#9B6A3E',
    motif: 'oven',
    ru: { name: 'Бурек', cat: 'Пирог', desc: 'Слоёный пирог из юфки с сочным мясом. В Сербии бурек без мяса — это не бурек!' },
    sr: { name: 'Burek', cat: 'Pita', desc: 'Slojevita pita od jufke sa sočnim mesom. U Srbiji, burek bez mesa — nije burek!' },
  },
  {
    id: 'gibanica',
    origin: 'sr',
    cats: ['Выпечка', 'Популярное'],
    time: 60,
    diff: 1,
    cal: 340,
    accent: '#9B7B3F',
    secondary: '#5A4222',
    motif: 'oven',
    ru: { name: 'Гибаница', cat: 'Пирог', desc: 'Сербский пирог из листов юфки с яйцом и рассольным сыром. Хрустит снаружи, тает внутри.' },
    sr: { name: 'Gibanica', cat: 'Pita', desc: 'Srpska pita od jufki sa jajima i sirom. Hrskava spolja, topi se iznutra.' },
  },
  {
    id: 'ustipci',
    origin: 'sr',
    cats: ['Выпечка', 'Закуски', 'За 30 минут'],
    time: 20,
    diff: 0,
    cal: 200,
    accent: '#C8893E',
    secondary: '#8B5E1E',
    motif: 'drip',
    ru: { name: 'Уштипцы', cat: 'Закуска', desc: 'Жареные тестяные шарики из кислого теста — сербские пончики. Хрустящие снаружи, мягкие внутри.' },
    sr: { name: 'Uštipci', cat: 'Predjelo', desc: 'Prženi krofni od kiselog testa — srpski krofni. Hrskavi spolja, meki iznutra.' },
  },
  {
    id: 'proja',
    origin: 'sr',
    cats: ['Выпечка', 'Постные'],
    time: 45,
    diff: 0,
    cal: 260,
    accent: '#E8C06A',
    secondary: '#C8893E',
    motif: 'wheat',
    ru: { name: 'Проя', cat: 'Хлеб', desc: 'Кукурузный хлеб, запечённый в масле — хрустящий, золотой. Простой и сытный хлеб балканских крестьян.' },
    sr: { name: 'Proja', cat: 'Hleb', desc: 'Kukuruzni hleb pečen u ulju — hrskav i zlatan. Jednostavan i sitan hleb balkanskih seljaka.' },
  },
  {
    id: 'kacamak',
    origin: 'sr',
    cats: ['Главное', 'Постные'],
    time: 30,
    diff: 0,
    cal: 290,
    accent: '#E8C06A',
    secondary: '#A07040',
    motif: 'drip',
    ru: { name: 'Качамак', cat: 'Каша', desc: 'Кукурузная полента с брынзой и сметаной — сербская каша крестьян. Согревает и насыщает.' },
    sr: { name: 'Kačamak', cat: 'Kaša', desc: 'Kukuruzna palenta sa sirom i pavlakom — srpska seljačka kaša.' },
  },
  {
    id: 'musaka',
    origin: 'sr',
    cats: ['Главное', 'Популярное'],
    time: 90,
    diff: 1,
    cal: 400,
    accent: '#8B5C3A',
    secondary: '#5A3A1E',
    motif: 'oven',
    ru: { name: 'Мусака', cat: 'Главное блюдо', desc: 'Запеканка из картофеля и мясного фарша под бéchamel. Балканская версия греческой классики.' },
    sr: { name: 'Musaka', cat: 'Glavno jelo', desc: 'Zapečeni krompir sa mlevenim mesom pod bešamelom. Balkanska verzija grčke klasike.' },
  },
  {
    id: 'srpska-sarma',
    origin: 'sr',
    cats: ['Главное', 'Балканский гриль'],
    time: 200,
    diff: 2,
    cal: 330,
    accent: '#6B8F6B',
    secondary: '#3F5944',
    motif: 'flame',
    ru: { name: 'Сербская сарма', cat: 'Главное блюдо', desc: 'Традиционная сарма с дополнением копчёного мяса и паприки. Кислее и острее русского варианта.' },
    sr: { name: 'Srpska sarma', cat: 'Glavno jelo', desc: 'Tradicionalna sarma sa suvim mesom i paprikom. Kisela i ljuća od ruske verzije.' },
  },
  {
    id: 'podvarak',
    origin: 'sr',
    cats: ['Главное', 'Постные'],
    time: 90,
    diff: 1,
    cal: 240,
    accent: '#7A6B3E',
    secondary: '#4A3E1E',
    motif: 'oven',
    ru: { name: 'Подварак', cat: 'Гарнир', desc: 'Квашеная капуста, тушёная с луком и паприкой в духовке. Идеальный гарнир к жаркому или шашлыку.' },
    sr: { name: 'Podvarak', cat: 'Prilog', desc: 'Kiseli kupus pečen sa lukom i paprikom u rerni. Savršen prilog uz pečenje ili roštilj.' },
  },
  {
    id: 'prebranac',
    origin: 'sr',
    cats: ['Закуски', 'Постные'],
    time: 120,
    diff: 1,
    cal: 280,
    accent: '#9B7B3F',
    secondary: '#6A5220',
    motif: 'oven',
    ru: { name: 'Пребранац', cat: 'Закуска', desc: 'Запечённая белая фасоль с луком и паприкой в горшочке. Классика сербского поста и рыночных лавок.' },
    sr: { name: 'Prebranac', cat: 'Predjelo', desc: 'Pečeni beli pasulj sa lukom i paprikom u lončiću. Klasika srpskog posta.' },
  },
  {
    id: 'pasulj',
    origin: 'sr',
    cats: ['Супы', 'Постные'],
    time: 100,
    diff: 1,
    cal: 260,
    accent: '#9B5C3A',
    secondary: '#6A3A1E',
    motif: 'flame',
    ru: { name: 'Пасуль', cat: 'Суп', desc: 'Густой фасолевый суп с копчёным мясом и паприкой. Национальное блюдо Сербии — горячее и сытное.' },
    sr: { name: 'Pasulj', cat: 'Supa', desc: 'Gusta supa od pasulja sa suvim mesom i paprikom. Nacionalno jelo Srbije.' },
  },
  {
    id: 'chorba',
    origin: 'sr',
    cats: ['Супы'],
    time: 50,
    diff: 0,
    cal: 180,
    accent: '#A05C2E',
    secondary: '#6A3A1A',
    motif: 'drip',
    ru: { name: 'Чорба', cat: 'Суп', desc: 'Пряный мясной суп с овощами — сербский вариант шурпы. Красный от паприки, душистый от специй.' },
    sr: { name: 'Čorba', cat: 'Supa', desc: 'Začinjena mesna supa sa povrćem. Crvena od paprike, mirisna od začina.' },
  },
  {
    id: 'teleca-chorba',
    origin: 'sr',
    cats: ['Супы'],
    time: 60,
    diff: 1,
    cal: 200,
    accent: '#D4986A',
    secondary: '#9B6A3E',
    motif: 'drip',
    ru: { name: 'Телячья чорба', cat: 'Суп', desc: 'Нежная светлая телятина с корнями петрушки и сельдерея. Ресторанная классика и домашний уют.' },
    sr: { name: 'Teleća čorba', cat: 'Supa', desc: 'Nežna svetla teletina sa peršunom i celerom. Restoranska klasika i domaća toplina.' },
  },
  {
    id: 'ajvar',
    origin: 'sr',
    cats: ['Закуски', 'Постные'],
    time: 180,
    diff: 1,
    cal: 90,
    accent: '#C84820',
    secondary: '#8B2E10',
    motif: 'flame',
    ru: { name: 'Айвар', cat: 'Закуска', desc: 'Сербское золото из запечённого красного перца и баклажана. Острый или сладкий — с хлебом или мясом.' },
    sr: { name: 'Ajvar', cat: 'Zimnica', desc: 'Srpsko zlato od pečene crvene paprike i patlidžana. Ljut ili sladak — uz hleb ili meso.' },
  },
  {
    id: 'kajmak',
    origin: 'sr',
    cats: ['Закуски', 'За 30 минут'],
    time: 10,
    diff: 0,
    cal: 180,
    accent: '#F5E8C8',
    secondary: '#C8893E',
    motif: 'drip',
    ru: { name: 'Каймак', cat: 'Молочное', desc: 'Сербский сливочный сыр из томлёных сливок молока — нежный, жирный, растворяется на языке.' },
    sr: { name: 'Kajmak', cat: 'Mleč​ni proizvod', desc: 'Srpski kremasti sir od kuvanog mleka — nežan, mastan, topi se na jeziku.' },
  },
  {
    id: 'srpska-salata',
    origin: 'sr',
    cats: ['Закуски', 'За 30 минут', 'Постные'],
    time: 10,
    diff: 0,
    cal: 80,
    accent: '#C84820',
    secondary: '#8B2E10',
    motif: 'leaf',
    ru: { name: 'Сербский салат', cat: 'Салат', desc: 'Томаты, перец, огурцы, лук и масло — свежее и простое. Появляется на каждом столе в Сербии.' },
    sr: { name: 'Srpska salata', cat: 'Salata', desc: 'Paradajz, paprika, krastavac, luk i ulje — sveže i jednostavno. Nalazi se na svakom stolu u Srbiji.' },
  },
  {
    id: 'shopska',
    origin: 'sr',
    cats: ['Закуски', 'За 30 минут', 'Постные'],
    time: 10,
    diff: 0,
    cal: 120,
    accent: '#3F5944',
    secondary: '#2A3D2E',
    motif: 'leaf',
    ru: { name: 'Шопска салата', cat: 'Салат', desc: 'Томаты, огурцы, перец с горой тёртой брынзы сверху. Болгарско-сербская классика на каждом столе.' },
    sr: { name: 'Šopska salata', cat: 'Salata', desc: 'Paradajz, krastavci, paprika sa gomilom rendanog sira odozgo. Bugarsko-srpska klasika.' },
  },
  {
    id: 'tulumbe',
    origin: 'sr',
    cats: ['Десерты'],
    time: 40,
    diff: 1,
    cal: 320,
    accent: '#C8893E',
    secondary: '#8B5E1E',
    motif: 'drip',
    ru: { name: 'Тулумбе', cat: 'Десерт', desc: 'Жареное тесто в сладком сиропе — балканский вариант чуррос. Золотистое, пропитанное, нежное.' },
    sr: { name: 'Tulumbe', cat: 'Desert', desc: 'Prženo testo u slatkom sirupu — balkanski čuros. Zlatno, mokro, nežno.' },
  },
  {
    id: 'baklava',
    origin: 'sr',
    cats: ['Десерты', 'Популярное'],
    time: 90,
    diff: 2,
    cal: 400,
    accent: '#E8C06A',
    secondary: '#C8893E',
    motif: 'wheat',
    ru: { name: 'Баклава', cat: 'Десерт', desc: 'Слоёная сладость из юфки с грецкими орехами и мёдом. Сладкое наследие Османской империи на Балканах.' },
    sr: { name: 'Baklava', cat: 'Desert', desc: 'Slojevita slatkiša od jufke sa orasima i medom. Slatko nasleđe Osmanskog carstva na Balkanu.' },
  },
  {
    id: 'tufahije',
    origin: 'sr',
    cats: ['Десерты'],
    time: 50,
    diff: 1,
    cal: 280,
    accent: '#9B5C3A',
    secondary: '#6A3A1E',
    motif: 'leaf',
    ru: { name: 'Туфахийе', cat: 'Десерт', desc: 'Яблоко, варёное в сахарном сиропе с грецкими орехами и розовой водой. Боснийская элегантность.' },
    sr: { name: 'Tufahije', cat: 'Desert', desc: 'Jabuka kuvana u šećernom sirupu sa orasima i ružinom vodom. Bosanska elegancija.' },
  },
  {
    id: 'slatko',
    origin: 'sr',
    cats: ['Десерты', 'За 30 минут'],
    time: 20,
    diff: 0,
    cal: 150,
    accent: '#8B2635',
    secondary: '#5A1520',
    motif: 'grape',
    ru: { name: 'Слатко', cat: 'Варенье', desc: 'Сербское варенье из целых ягод или фруктов — гостеприимство в чайной ложке с водой и кофе.' },
    sr: { name: 'Slatko', cat: 'Džem', desc: 'Srpski džem od celih bobica ili voća — gostoprimstvo u kašičici uz vodu i kafu.' },
  },
];

export const CATEGORIES_RU = ['Все', 'Популярное', 'Главное', 'Супы', 'Балканский гриль', 'Выпечка', 'Десерты', 'Закуски', 'Постные', 'За 30 минут'];
export const CATEGORIES_SR = ['Sve', 'Popularno', 'Glavno', 'Supe', 'Roštilj', 'Pecivo', 'Deserti', 'Predjela', 'Posno', 'Za 30 minuta'];
